name: dauflop_store
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  image_picker: ^1.1.2
  month_year_picker: ^0.4.0+1
  firebase_auth: ^5.6.0
  google_sign_in: ^6.3.0

  # --- NEW DEPENDENCIES FOR VNPAY ---
  # For opening URLs
  url_launcher: ^6.3.0
  # For creating the secure hash (checksum)
  crypto: ^3.0.3
  # For formatting dates and numbers
  intl: ^0.19.0 


  cupertino_icons: ^1.0.8
  convert: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/
    - assets/images/
