// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGcAI_s-RJhdZjsZ4mmbv2T1qyrjsuLMk',
    appId: '1:80413761686:web:34a29e332eb229fa3622b7',
    messagingSenderId: '80413761686',
    projectId: 'dauflop-store',
    authDomain: 'dauflop-store.firebaseapp.com',
    storageBucket: 'dauflop-store.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzpwjqUH5WgeHrUxkD3151de-DGvdzm8A',
    appId: '1:80413761686:android:e882025aa514283b3622b7',
    messagingSenderId: '80413761686',
    projectId: 'dauflop-store',
    storageBucket: 'dauflop-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL5N22wrQQMWJ02TPjOdvlBrpSE5rColU',
    appId: '1:80413761686:ios:d2684dcefa6481053622b7',
    messagingSenderId: '80413761686',
    projectId: 'dauflop-store',
    storageBucket: 'dauflop-store.firebasestorage.app',
    iosBundleId: 'com.example.dauflopStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL5N22wrQQMWJ02TPjOdvlBrpSE5rColU',
    appId: '1:80413761686:ios:d2684dcefa6481053622b7',
    messagingSenderId: '80413761686',
    projectId: 'dauflop-store',
    storageBucket: 'dauflop-store.firebasestorage.app',
    iosBundleId: 'com.example.dauflopStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGcAI_s-RJhdZjsZ4mmbv2T1qyrjsuLMk',
    appId: '1:80413761686:web:c82bc51d872ad9d73622b7',
    messagingSenderId: '80413761686',
    projectId: 'dauflop-store',
    authDomain: 'dauflop-store.firebaseapp.com',
    storageBucket: 'dauflop-store.firebasestorage.app',
  );
}
